# Generated by Django 4.2.3 on 2023-07-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("position", models.CharField(max_length=50)),
                ("univ", models.CharField(max_length=50)),
                ("session", models.CharField(max_length=50)),
                ("ph", models.CharField(max_length=50)),
                ("cph", models.CharField(max_length=50)),
                ("cemail", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=50)),
                ("cgpa", models.CharField(max_length=50)),
                ("skill_1", models.CharField(max_length=50)),
                ("skill_2", models.CharField(max_length=50)),
                ("skill_3", models.CharField(max_length=50)),
                ("skill_4", models.CharField(max_length=50)),
                ("skill_5", models.CharField(max_length=50)),
                ("skill_6", models.CharField(max_length=50)),
                ("xp_1_title", models.CharField(max_length=50)),
                ("xp_2_title", models.CharField(max_length=50)),
                ("xp_3_title", models.CharField(max_length=50)),
                ("xp_4_title", models.CharField(max_length=50)),
                ("xp_5_title", models.CharField(max_length=50)),
                ("xp_6_title", models.CharField(max_length=50)),
                ("xp_1_desc", models.CharField(max_length=50)),
                ("xp_2_desc", models.CharField(max_length=50)),
                ("xp_3_desc", models.CharField(max_length=50)),
                ("xp_4_desc", models.CharField(max_length=50)),
                ("xp_5_desc", models.CharField(max_length=50)),
                ("xp_6_desc", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Webapp.user"
                    ),
                ),
            ],
        ),
    ]
