# Generated by Django 2.0.4 on 2018-06-17 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180617_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_info',
            name='name',
            field=models.TextField(default='noname'),
        ),
        migrations.AddField(
            model_name='reg_info',
            name='phone',
            field=models.IntegerField(default=8888),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2018, 6, 18)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='password',
            field=models.TextField(default='admin'),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=48, primary_key=True, serialize=False, unique=True),
        ),
    ]
