# Generated by Django 2.0.4 on 2018-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180618_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=111, primary_key=True, serialize=False, unique=True),
        ),
    ]
