# Generated by Django 2.0.4 on 2018-06-18 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20180618_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2018, 6, 19)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=99, primary_key=True, serialize=False, unique=True),
        ),
    ]
