# Generated by Django 2.0.4 on 2018-06-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180619_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=48, primary_key=True, serialize=False, unique=True),
        ),
    ]
