# Generated by Django 2.0.4 on 2018-06-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20180619_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=93, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_1_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_2_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_3_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_4_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_5_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_data',
            name='xp_6_session',
            field=models.DateField(),
        ),
    ]
