# Generated by Django 2.0.4 on 2018-06-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180619_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=123, primary_key=True, serialize=False, unique=True),
        ),
    ]
