# Generated by Django 2.0.4 on 2018-06-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20180619_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.date(2018, 6, 26)),
        ),
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=129, primary_key=True, serialize=False, unique=True),
        ),
    ]
